name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # trigger on semantic version tags

  release:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup git-mkver
        uses: cperezabo/setup-git-mkver@v1.2.0
        with:
          version: "1.3.0"

#      - name: Generate version
#        id: generate-version
#        run: |
#          export VERSION=$(git mkver next)
#          echo $VERSION
#          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
#          #echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          token: ${{ secrets.PAT }} # required to trigger release-publish, see https://stackoverflow.com/questions/69063452/github-actions-on-release-created-workflow-trigger-not-working